# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Run the unit tests"
  lane :unit_tests do
    gradle(task: "test")
  end

  desc "Run all tests with code coverage"
  lane :all_tests do
    gradle(task: "combinedTestReportDebug")
  end

  desc "Deploy the app to the internal track"
  lane :deploy_internal do
    gradle(task: "bundleRelease")
    supply(
      track: 'internal',
      aab: lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH].to_s
    )
  end
end
